### ISSUE TITLE
Error from docker-compose up command

### ISSUE THREAD

**Issue by RustEngineer** [security-union/rust-for-backend-development#6]
#0 104.1 error: failed to compile `cargo-watch v8.1.1`, intermediate artifacts can be found at `/tmp/cargo-installJm7xph`
#0 104.1
#0 104.1 Caused by:
#0 104.1   failed to parse manifest at `/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/zbus_names-2.1.0/Cargo.toml`
#0 104.1
#0 104.1 Caused by:
#0 104.1   feature `resolver` is required
#0 104.1
#0 104.1 consider adding `cargo-features = ["resolver"]` to the manifest
#0 104.1 error: could not find `=` in registry `https://github.com/rust-lang/crates.io-index`
#0 104.1 error: could not find `7.4.0` in registry `https://github.com/rust-lang/crates.io-index`
#0 104.1      Summary Failed to install cargo-watch, =, 7.4.0 (see error(s) above).
#0 104.1 error: some crates failed to install
------
failed to solve: executor failed running [/bin/sh -c cargo install cargo-watch = "7.4.0"]: exit code: 101

I get the above error after docker-compose up command. Any advice is appreciated.

**Comment by darioalessandro** [comment]
Thanks for reporting this! I’ll take a look today

**Comment by darioalessandro** [comment]
Which lesson are you working on @RustEngineer ?

**Comment by RustEngineer** [comment]
Lesson 4

**Comment by darioalessandro** [comment]
Ok, I’ll get back to you by 8 pm eastern

**Comment by darioalessandro** [comment]
I was able to reproduce it, I am fixing it, I'll tag you on the PR

**Comment by darioalessandro** [comment]
@RustEngineer it is fixed :) 

Please pull the latest code and run:

```
git pull origin master
docker-compose build
docker-compose up
```

Thanks for bringing this to my attention!!!

**Comment by darioalessandro** [comment]
I also fixed project 5

**Comment by RustEngineer** [comment]
Worked perfectly. Much appreciated!

**Comment by darioalessandro** [comment]
You're welcome! thanks for watching!
